import './globals.css'
// import { Inter } from 'next/font/google'
import { Urbanist, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap'})

const urbanist = Urbanist({ 
  subsets: ['latin'],
  weight: ['100', '300'],
  variable: '--font-urbanist',
});

export const metadata = {
  title: 'Karnovah',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${urbanist.variable} font-sans`}>{children}</body>
    </html>
  )
}
