import './globals.css'
import { Inter } from 'next/font/google'
import { Urbanist } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

const urbanist = Urbanist({ 
  subsets: ['latin'],
  weight: ['100', '300'],
  variable: '--font-urbanist',
});

export const metadata = {
  title: 'Karnovah',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} font-sans`}>{children}</body>
    </html>
  )
}
